INSERT INTO public.artifacts (id, title, description, origin, era, category, images, buy_now_price, estimated_value, status, is_featured)
VALUES 
('f47ac10b-58cc-4372-a567-0e02b2c3d479', 'Byzantine Gold Pectoral Cross', 'An exquisite gold pectoral cross from the Byzantine Empire, featuring intricate filigree work and inlaid garnets. This remarkable piece served as a symbol of faith and authority for high-ranking clergy.', 'Constantinople', '6th Century AD', 'antiquity', '{"/buy/item-1.jpg"}', 580000, 580000, 'available', true),
('f47ac10c-58cc-4372-a567-0e02b2c3d479', 'Ming Dynasty Jade Dragon', 'A masterfully carved nephrite jade dragon sculpture from the Ming Dynasty. The sinuous form and translucent green stone exemplify the pinnacle of Chinese jade carving artistry.', 'China', '15th Century', 'sculpture', '{"/buy/item-2.jpg"}', 1450000, 1450000, 'available', true),
('f47ac10d-58cc-4372-a567-0e02b2c3d479', 'Illuminated Book of Hours', 'A Flemish illuminated manuscript with lavish gold leaf decorations and vivid miniature paintings. Each page is a testament to medieval artistic devotion and craftsmanship.', 'Bruges, Flanders', 'c. 1480', 'manuscript', '{"/buy/item-3.jpg"}', 420000, 420000, 'available', true),
('f47ac10e-58cc-4372-a567-0e02b2c3d479', 'Edo Period Samurai Katana', 'A superbly preserved katana with a folded-steel blade by master swordsmith Tadayoshi. The tsuba features gold inlay depicting a crane in flight, and the scabbard is lacquered with gold dust.', 'Japan', '17th Century', 'arms_and_armor', '{"/buy/item-4.jpg"}', 890000, 890000, 'available', true),
('f47ac10f-58cc-4372-a567-0e02b2c3d479', 'Royal Egyptian Scarab Amulet', 'A large lapis lazuli scarab amulet inscribed with hieroglyphics bearing the cartouche of a pharaoh. Exceptional preservation with vivid blue stone and gold-leaf detailing.', 'Thebes, Egypt', '18th Dynasty', 'antiquity', '{"/buy/item-5.jpg"}', 320000, 320000, 'available', true),
('f47ac11a-58cc-4372-a567-0e02b2c3d479', 'Venetian Etched Glass Mirror', 'An ornate Murano glass mirror with hand-etched floral motifs and gilt-bronze frame. This piece once adorned the private chambers of a Venetian palazzo along the Grand Canal.', 'Venice, Italy', '18th Century', 'decorative_art', '{"/buy/item-6.jpg"}', 275000, 275000, 'available', true),
('f47ac11b-58cc-4372-a567-0e02b2c3d479', 'Safavid Silk Court Carpet', 'A museum-quality silk carpet with over 800 knots per square inch, featuring a central medallion design in indigo, crimson, and gold. Woven in the royal workshops of Isfahan.', 'Isfahan, Persia', '17th Century', 'textile', '{"/buy/item-7.jpg"}', 1200000, 1200000, 'available', true),
('f47ac11c-58cc-4372-a567-0e02b2c3d479', 'Marble Bust of Emperor Hadrian', 'A near-complete Roman marble portrait bust of Emperor Hadrian with remarkably preserved facial features. Traces of original polychrome pigment remain on the hair and laurel wreath.', 'Rome, Italy', '2nd Century AD', 'sculpture', '{"/buy/item-8.jpg"}', 2100000, 2100000, 'available', true),
('f47ac11d-58cc-4372-a567-0e02b2c3d479', 'Imperial Fabergé Easter Egg', 'A jewelled Easter egg crafted by the House of Fabergé in gold, enamel, and precious stones. The surprise mechanism reveals a miniature golden carriage with functioning wheels.', 'St. Petersburg, Russia', 'c. 1900', 'objets_d_art', '{"/buy/item-9.jpg"}', 3800000, 3800000, 'available', true),
('f47ac11e-58cc-4372-a567-0e02b2c3d479', 'Aztec Obsidian Calendar Stone', 'A rare volcanic obsidian disc carved with the Aztec calendar motif, featuring Tonatiuh at center surrounded by the four previous suns. Exceptional craftsmanship with mirror-polished surface.', 'Tenochtitlan, Mexico', '15th Century', 'antiquity', '{"/buy/item-10.jpg"}', 950000, 950000, 'available', true)
ON CONFLICT (id) DO NOTHING;
